//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DSW2_Proyecto_Huron_Azul.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Huron_Azul_ServiceSoap11Binding", Namespace="http://service")]
    public partial class Huron_Azul_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback u_editarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ci_listarOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaBeanPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback pro_autogeneraOperationCompleted;
        
        private System.Threading.SendOrPostCallback ped_detalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback cat_listarOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaBeanProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ped_listarOperationCompleted;
        
        private System.Threading.SendOrPostCallback u_registrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ped_registrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback pro_editarOperationCompleted;
        
        private System.Threading.SendOrPostCallback u_logueoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaBeanPedidoDetalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback pro_inactivarOperationCompleted;
        
        private System.Threading.SendOrPostCallback pro_listarOperationCompleted;
        
        private System.Threading.SendOrPostCallback pro_registrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ci_cancelarOperationCompleted;
        
        private System.Threading.SendOrPostCallback s_listarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ci_detalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ci_registrarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Huron_Azul_Service() {
            this.Url = global::DSW2_Proyecto_Huron_Azul.Properties.Settings.Default.DSW2_Proyecto_Huron_Azul_localhost_Huron_Azul_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event u_editarCompletedEventHandler u_editarCompleted;
        
        /// <remarks/>
        public event ci_listarCompletedEventHandler ci_listarCompleted;
        
        /// <remarks/>
        public event listaBeanPedidoCompletedEventHandler listaBeanPedidoCompleted;
        
        /// <remarks/>
        public event pro_autogeneraCompletedEventHandler pro_autogeneraCompleted;
        
        /// <remarks/>
        public event ped_detalleCompletedEventHandler ped_detalleCompleted;
        
        /// <remarks/>
        public event cat_listarCompletedEventHandler cat_listarCompleted;
        
        /// <remarks/>
        public event listaBeanProductoCompletedEventHandler listaBeanProductoCompleted;
        
        /// <remarks/>
        public event ped_listarCompletedEventHandler ped_listarCompleted;
        
        /// <remarks/>
        public event u_registrarCompletedEventHandler u_registrarCompleted;
        
        /// <remarks/>
        public event ped_registrarCompletedEventHandler ped_registrarCompleted;
        
        /// <remarks/>
        public event pro_editarCompletedEventHandler pro_editarCompleted;
        
        /// <remarks/>
        public event u_logueoCompletedEventHandler u_logueoCompleted;
        
        /// <remarks/>
        public event listaBeanPedidoDetalleCompletedEventHandler listaBeanPedidoDetalleCompleted;
        
        /// <remarks/>
        public event pro_inactivarCompletedEventHandler pro_inactivarCompleted;
        
        /// <remarks/>
        public event pro_listarCompletedEventHandler pro_listarCompleted;
        
        /// <remarks/>
        public event pro_registrarCompletedEventHandler pro_registrarCompleted;
        
        /// <remarks/>
        public event ci_cancelarCompletedEventHandler ci_cancelarCompleted;
        
        /// <remarks/>
        public event s_listarCompletedEventHandler s_listarCompleted;
        
        /// <remarks/>
        public event ci_detalleCompletedEventHandler ci_detalleCompleted;
        
        /// <remarks/>
        public event ci_registrarCompletedEventHandler ci_registrarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:u_editar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string u_editar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BeanUsuario u) {
            object[] results = this.Invoke("u_editar", new object[] {
                        u});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void u_editarAsync(BeanUsuario u) {
            this.u_editarAsync(u, null);
        }
        
        /// <remarks/>
        public void u_editarAsync(BeanUsuario u, object userState) {
            if ((this.u_editarOperationCompleted == null)) {
                this.u_editarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onu_editarOperationCompleted);
            }
            this.InvokeAsync("u_editar", new object[] {
                        u}, this.u_editarOperationCompleted, userState);
        }
        
        private void Onu_editarOperationCompleted(object arg) {
            if ((this.u_editarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.u_editarCompleted(this, new u_editarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ci_listar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public BeanCitaTuneado[] ci_listar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario) {
            object[] results = this.Invoke("ci_listar", new object[] {
                        usuario});
            return ((BeanCitaTuneado[])(results[0]));
        }
        
        /// <remarks/>
        public void ci_listarAsync(string usuario) {
            this.ci_listarAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ci_listarAsync(string usuario, object userState) {
            if ((this.ci_listarOperationCompleted == null)) {
                this.ci_listarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onci_listarOperationCompleted);
            }
            this.InvokeAsync("ci_listar", new object[] {
                        usuario}, this.ci_listarOperationCompleted, userState);
        }
        
        private void Onci_listarOperationCompleted(object arg) {
            if ((this.ci_listarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ci_listarCompleted(this, new ci_listarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:listaBeanPedido", RequestNamespace="http://service", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void listaBeanPedido([System.Xml.Serialization.XmlElementAttribute("lista_pedido", IsNullable=true)] BeanPedido[] lista_pedido) {
            this.Invoke("listaBeanPedido", new object[] {
                        lista_pedido});
        }
        
        /// <remarks/>
        public void listaBeanPedidoAsync(BeanPedido[] lista_pedido) {
            this.listaBeanPedidoAsync(lista_pedido, null);
        }
        
        /// <remarks/>
        public void listaBeanPedidoAsync(BeanPedido[] lista_pedido, object userState) {
            if ((this.listaBeanPedidoOperationCompleted == null)) {
                this.listaBeanPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaBeanPedidoOperationCompleted);
            }
            this.InvokeAsync("listaBeanPedido", new object[] {
                        lista_pedido}, this.listaBeanPedidoOperationCompleted, userState);
        }
        
        private void OnlistaBeanPedidoOperationCompleted(object arg) {
            if ((this.listaBeanPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaBeanPedidoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:pro_autogenera", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string pro_autogenera() {
            object[] results = this.Invoke("pro_autogenera", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pro_autogeneraAsync() {
            this.pro_autogeneraAsync(null);
        }
        
        /// <remarks/>
        public void pro_autogeneraAsync(object userState) {
            if ((this.pro_autogeneraOperationCompleted == null)) {
                this.pro_autogeneraOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpro_autogeneraOperationCompleted);
            }
            this.InvokeAsync("pro_autogenera", new object[0], this.pro_autogeneraOperationCompleted, userState);
        }
        
        private void Onpro_autogeneraOperationCompleted(object arg) {
            if ((this.pro_autogeneraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pro_autogeneraCompleted(this, new pro_autogeneraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ped_detalle", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public BeanPedidoTuneado ped_detalle([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string codpedido) {
            object[] results = this.Invoke("ped_detalle", new object[] {
                        codpedido});
            return ((BeanPedidoTuneado)(results[0]));
        }
        
        /// <remarks/>
        public void ped_detalleAsync(string codpedido) {
            this.ped_detalleAsync(codpedido, null);
        }
        
        /// <remarks/>
        public void ped_detalleAsync(string codpedido, object userState) {
            if ((this.ped_detalleOperationCompleted == null)) {
                this.ped_detalleOperationCompleted = new System.Threading.SendOrPostCallback(this.Onped_detalleOperationCompleted);
            }
            this.InvokeAsync("ped_detalle", new object[] {
                        codpedido}, this.ped_detalleOperationCompleted, userState);
        }
        
        private void Onped_detalleOperationCompleted(object arg) {
            if ((this.ped_detalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ped_detalleCompleted(this, new ped_detalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:cat_listar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public BeanCategoriaProd[] cat_listar() {
            object[] results = this.Invoke("cat_listar", new object[0]);
            return ((BeanCategoriaProd[])(results[0]));
        }
        
        /// <remarks/>
        public void cat_listarAsync() {
            this.cat_listarAsync(null);
        }
        
        /// <remarks/>
        public void cat_listarAsync(object userState) {
            if ((this.cat_listarOperationCompleted == null)) {
                this.cat_listarOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncat_listarOperationCompleted);
            }
            this.InvokeAsync("cat_listar", new object[0], this.cat_listarOperationCompleted, userState);
        }
        
        private void Oncat_listarOperationCompleted(object arg) {
            if ((this.cat_listarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cat_listarCompleted(this, new cat_listarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:listaBeanProducto", RequestNamespace="http://service", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void listaBeanProducto([System.Xml.Serialization.XmlElementAttribute("lista_prod", IsNullable=true)] BeanProducto[] lista_prod) {
            this.Invoke("listaBeanProducto", new object[] {
                        lista_prod});
        }
        
        /// <remarks/>
        public void listaBeanProductoAsync(BeanProducto[] lista_prod) {
            this.listaBeanProductoAsync(lista_prod, null);
        }
        
        /// <remarks/>
        public void listaBeanProductoAsync(BeanProducto[] lista_prod, object userState) {
            if ((this.listaBeanProductoOperationCompleted == null)) {
                this.listaBeanProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaBeanProductoOperationCompleted);
            }
            this.InvokeAsync("listaBeanProducto", new object[] {
                        lista_prod}, this.listaBeanProductoOperationCompleted, userState);
        }
        
        private void OnlistaBeanProductoOperationCompleted(object arg) {
            if ((this.listaBeanProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaBeanProductoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ped_listar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public BeanPedidoTuneado[] ped_listar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string usuario) {
            object[] results = this.Invoke("ped_listar", new object[] {
                        usuario});
            return ((BeanPedidoTuneado[])(results[0]));
        }
        
        /// <remarks/>
        public void ped_listarAsync(string usuario) {
            this.ped_listarAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ped_listarAsync(string usuario, object userState) {
            if ((this.ped_listarOperationCompleted == null)) {
                this.ped_listarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onped_listarOperationCompleted);
            }
            this.InvokeAsync("ped_listar", new object[] {
                        usuario}, this.ped_listarOperationCompleted, userState);
        }
        
        private void Onped_listarOperationCompleted(object arg) {
            if ((this.ped_listarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ped_listarCompleted(this, new ped_listarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:u_registrar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string u_registrar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BeanUsuario u) {
            object[] results = this.Invoke("u_registrar", new object[] {
                        u});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void u_registrarAsync(BeanUsuario u) {
            this.u_registrarAsync(u, null);
        }
        
        /// <remarks/>
        public void u_registrarAsync(BeanUsuario u, object userState) {
            if ((this.u_registrarOperationCompleted == null)) {
                this.u_registrarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onu_registrarOperationCompleted);
            }
            this.InvokeAsync("u_registrar", new object[] {
                        u}, this.u_registrarOperationCompleted, userState);
        }
        
        private void Onu_registrarOperationCompleted(object arg) {
            if ((this.u_registrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.u_registrarCompleted(this, new u_registrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ped_registrar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string ped_registrar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BeanPedido p, [System.Xml.Serialization.XmlElementAttribute("lista_detalle", IsNullable=true)] BeanPedidoDetalle[] lista_detalle) {
            object[] results = this.Invoke("ped_registrar", new object[] {
                        p,
                        lista_detalle});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ped_registrarAsync(BeanPedido p, BeanPedidoDetalle[] lista_detalle) {
            this.ped_registrarAsync(p, lista_detalle, null);
        }
        
        /// <remarks/>
        public void ped_registrarAsync(BeanPedido p, BeanPedidoDetalle[] lista_detalle, object userState) {
            if ((this.ped_registrarOperationCompleted == null)) {
                this.ped_registrarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onped_registrarOperationCompleted);
            }
            this.InvokeAsync("ped_registrar", new object[] {
                        p,
                        lista_detalle}, this.ped_registrarOperationCompleted, userState);
        }
        
        private void Onped_registrarOperationCompleted(object arg) {
            if ((this.ped_registrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ped_registrarCompleted(this, new ped_registrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:pro_editar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string pro_editar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BeanProducto p) {
            object[] results = this.Invoke("pro_editar", new object[] {
                        p});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pro_editarAsync(BeanProducto p) {
            this.pro_editarAsync(p, null);
        }
        
        /// <remarks/>
        public void pro_editarAsync(BeanProducto p, object userState) {
            if ((this.pro_editarOperationCompleted == null)) {
                this.pro_editarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpro_editarOperationCompleted);
            }
            this.InvokeAsync("pro_editar", new object[] {
                        p}, this.pro_editarOperationCompleted, userState);
        }
        
        private void Onpro_editarOperationCompleted(object arg) {
            if ((this.pro_editarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pro_editarCompleted(this, new pro_editarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:u_logueo", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public BeanUsuario u_logueo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pass) {
            object[] results = this.Invoke("u_logueo", new object[] {
                        id,
                        pass});
            return ((BeanUsuario)(results[0]));
        }
        
        /// <remarks/>
        public void u_logueoAsync(string id, string pass) {
            this.u_logueoAsync(id, pass, null);
        }
        
        /// <remarks/>
        public void u_logueoAsync(string id, string pass, object userState) {
            if ((this.u_logueoOperationCompleted == null)) {
                this.u_logueoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onu_logueoOperationCompleted);
            }
            this.InvokeAsync("u_logueo", new object[] {
                        id,
                        pass}, this.u_logueoOperationCompleted, userState);
        }
        
        private void Onu_logueoOperationCompleted(object arg) {
            if ((this.u_logueoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.u_logueoCompleted(this, new u_logueoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:listaBeanPedidoDetalle", RequestNamespace="http://service", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void listaBeanPedidoDetalle([System.Xml.Serialization.XmlElementAttribute("lista_detalle", IsNullable=true)] BeanPedidoDetalle[] lista_detalle) {
            this.Invoke("listaBeanPedidoDetalle", new object[] {
                        lista_detalle});
        }
        
        /// <remarks/>
        public void listaBeanPedidoDetalleAsync(BeanPedidoDetalle[] lista_detalle) {
            this.listaBeanPedidoDetalleAsync(lista_detalle, null);
        }
        
        /// <remarks/>
        public void listaBeanPedidoDetalleAsync(BeanPedidoDetalle[] lista_detalle, object userState) {
            if ((this.listaBeanPedidoDetalleOperationCompleted == null)) {
                this.listaBeanPedidoDetalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaBeanPedidoDetalleOperationCompleted);
            }
            this.InvokeAsync("listaBeanPedidoDetalle", new object[] {
                        lista_detalle}, this.listaBeanPedidoDetalleOperationCompleted, userState);
        }
        
        private void OnlistaBeanPedidoDetalleOperationCompleted(object arg) {
            if ((this.listaBeanPedidoDetalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaBeanPedidoDetalleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:pro_inactivar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string pro_inactivar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string codprod) {
            object[] results = this.Invoke("pro_inactivar", new object[] {
                        codprod});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pro_inactivarAsync(string codprod) {
            this.pro_inactivarAsync(codprod, null);
        }
        
        /// <remarks/>
        public void pro_inactivarAsync(string codprod, object userState) {
            if ((this.pro_inactivarOperationCompleted == null)) {
                this.pro_inactivarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpro_inactivarOperationCompleted);
            }
            this.InvokeAsync("pro_inactivar", new object[] {
                        codprod}, this.pro_inactivarOperationCompleted, userState);
        }
        
        private void Onpro_inactivarOperationCompleted(object arg) {
            if ((this.pro_inactivarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pro_inactivarCompleted(this, new pro_inactivarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:pro_listar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public BeanProducto[] pro_listar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TIPO_USUARIO, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_CATPROD, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string P_DESCPROD) {
            object[] results = this.Invoke("pro_listar", new object[] {
                        TIPO_USUARIO,
                        P_CATPROD,
                        P_DESCPROD});
            return ((BeanProducto[])(results[0]));
        }
        
        /// <remarks/>
        public void pro_listarAsync(string TIPO_USUARIO, string P_CATPROD, string P_DESCPROD) {
            this.pro_listarAsync(TIPO_USUARIO, P_CATPROD, P_DESCPROD, null);
        }
        
        /// <remarks/>
        public void pro_listarAsync(string TIPO_USUARIO, string P_CATPROD, string P_DESCPROD, object userState) {
            if ((this.pro_listarOperationCompleted == null)) {
                this.pro_listarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpro_listarOperationCompleted);
            }
            this.InvokeAsync("pro_listar", new object[] {
                        TIPO_USUARIO,
                        P_CATPROD,
                        P_DESCPROD}, this.pro_listarOperationCompleted, userState);
        }
        
        private void Onpro_listarOperationCompleted(object arg) {
            if ((this.pro_listarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pro_listarCompleted(this, new pro_listarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:pro_registrar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string pro_registrar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BeanProducto p) {
            object[] results = this.Invoke("pro_registrar", new object[] {
                        p});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pro_registrarAsync(BeanProducto p) {
            this.pro_registrarAsync(p, null);
        }
        
        /// <remarks/>
        public void pro_registrarAsync(BeanProducto p, object userState) {
            if ((this.pro_registrarOperationCompleted == null)) {
                this.pro_registrarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpro_registrarOperationCompleted);
            }
            this.InvokeAsync("pro_registrar", new object[] {
                        p}, this.pro_registrarOperationCompleted, userState);
        }
        
        private void Onpro_registrarOperationCompleted(object arg) {
            if ((this.pro_registrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pro_registrarCompleted(this, new pro_registrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ci_cancelar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string ci_cancelar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nrocita) {
            object[] results = this.Invoke("ci_cancelar", new object[] {
                        nrocita});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ci_cancelarAsync(string nrocita) {
            this.ci_cancelarAsync(nrocita, null);
        }
        
        /// <remarks/>
        public void ci_cancelarAsync(string nrocita, object userState) {
            if ((this.ci_cancelarOperationCompleted == null)) {
                this.ci_cancelarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onci_cancelarOperationCompleted);
            }
            this.InvokeAsync("ci_cancelar", new object[] {
                        nrocita}, this.ci_cancelarOperationCompleted, userState);
        }
        
        private void Onci_cancelarOperationCompleted(object arg) {
            if ((this.ci_cancelarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ci_cancelarCompleted(this, new ci_cancelarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:s_listar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public BeanSede[] s_listar() {
            object[] results = this.Invoke("s_listar", new object[0]);
            return ((BeanSede[])(results[0]));
        }
        
        /// <remarks/>
        public void s_listarAsync() {
            this.s_listarAsync(null);
        }
        
        /// <remarks/>
        public void s_listarAsync(object userState) {
            if ((this.s_listarOperationCompleted == null)) {
                this.s_listarOperationCompleted = new System.Threading.SendOrPostCallback(this.Ons_listarOperationCompleted);
            }
            this.InvokeAsync("s_listar", new object[0], this.s_listarOperationCompleted, userState);
        }
        
        private void Ons_listarOperationCompleted(object arg) {
            if ((this.s_listarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.s_listarCompleted(this, new s_listarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ci_detalle", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public BeanCitaTuneado ci_detalle([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nrocita) {
            object[] results = this.Invoke("ci_detalle", new object[] {
                        nrocita});
            return ((BeanCitaTuneado)(results[0]));
        }
        
        /// <remarks/>
        public void ci_detalleAsync(string nrocita) {
            this.ci_detalleAsync(nrocita, null);
        }
        
        /// <remarks/>
        public void ci_detalleAsync(string nrocita, object userState) {
            if ((this.ci_detalleOperationCompleted == null)) {
                this.ci_detalleOperationCompleted = new System.Threading.SendOrPostCallback(this.Onci_detalleOperationCompleted);
            }
            this.InvokeAsync("ci_detalle", new object[] {
                        nrocita}, this.ci_detalleOperationCompleted, userState);
        }
        
        private void Onci_detalleOperationCompleted(object arg) {
            if ((this.ci_detalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ci_detalleCompleted(this, new ci_detalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ci_registrar", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string ci_registrar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] BeanCita c) {
            object[] results = this.Invoke("ci_registrar", new object[] {
                        c});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ci_registrarAsync(BeanCita c) {
            this.ci_registrarAsync(c, null);
        }
        
        /// <remarks/>
        public void ci_registrarAsync(BeanCita c, object userState) {
            if ((this.ci_registrarOperationCompleted == null)) {
                this.ci_registrarOperationCompleted = new System.Threading.SendOrPostCallback(this.Onci_registrarOperationCompleted);
            }
            this.InvokeAsync("ci_registrar", new object[] {
                        c}, this.ci_registrarOperationCompleted, userState);
        }
        
        private void Onci_registrarOperationCompleted(object arg) {
            if ((this.ci_registrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ci_registrarCompleted(this, new ci_registrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans/xsd")]
    public partial class BeanUsuario {
        
        private string aPEUSUARIOField;
        
        private string cODUSUARIOField;
        
        private string dIRECCIONField;
        
        private string dNIField;
        
        private string eMAILField;
        
        private string eSTADOField;
        
        private string fECNACField;
        
        private string iDLOGINField;
        
        private string nOMUSUARIOField;
        
        private string pASSWORDField;
        
        private string sEXOField;
        
        private string tELEFONOField;
        
        private string tIPOUSUARIOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string APEUSUARIO {
            get {
                return this.aPEUSUARIOField;
            }
            set {
                this.aPEUSUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODUSUARIO {
            get {
                return this.cODUSUARIOField;
            }
            set {
                this.cODUSUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECNAC {
            get {
                return this.fECNACField;
            }
            set {
                this.fECNACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IDLOGIN {
            get {
                return this.iDLOGINField;
            }
            set {
                this.iDLOGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NOMUSUARIO {
            get {
                return this.nOMUSUARIOField;
            }
            set {
                this.nOMUSUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SEXO {
            get {
                return this.sEXOField;
            }
            set {
                this.sEXOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TELEFONO {
            get {
                return this.tELEFONOField;
            }
            set {
                this.tELEFONOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TIPOUSUARIO {
            get {
                return this.tIPOUSUARIOField;
            }
            set {
                this.tIPOUSUARIOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans/xsd")]
    public partial class BeanCita {
        
        private string cLIENTEField;
        
        private string cODCITAField;
        
        private string eSTADOField;
        
        private string fECHA_HORAField;
        
        private string lUGARATENCIONField;
        
        private string sEDEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODCITA {
            get {
                return this.cODCITAField;
            }
            set {
                this.cODCITAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHA_HORA {
            get {
                return this.fECHA_HORAField;
            }
            set {
                this.fECHA_HORAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LUGARATENCION {
            get {
                return this.lUGARATENCIONField;
            }
            set {
                this.lUGARATENCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SEDE {
            get {
                return this.sEDEField;
            }
            set {
                this.sEDEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans/xsd")]
    public partial class BeanSede {
        
        private string cODSEDEField;
        
        private string dIRSEDEField;
        
        private string rEFSEDEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODSEDE {
            get {
                return this.cODSEDEField;
            }
            set {
                this.cODSEDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DIRSEDE {
            get {
                return this.dIRSEDEField;
            }
            set {
                this.dIRSEDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFSEDE {
            get {
                return this.rEFSEDEField;
            }
            set {
                this.rEFSEDEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans/xsd")]
    public partial class BeanPedidoDetalle {
        
        private string cANTIDADField;
        
        private string cODPEDIDOField;
        
        private string mONTOField;
        
        private string pRODUCTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODPEDIDO {
            get {
                return this.cODPEDIDOField;
            }
            set {
                this.cODPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MONTO {
            get {
                return this.mONTOField;
            }
            set {
                this.mONTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRODUCTO {
            get {
                return this.pRODUCTOField;
            }
            set {
                this.pRODUCTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans/xsd")]
    public partial class BeanProducto {
        
        private string cATPRODField;
        
        private string cODPRODField;
        
        private string dESCPRODField;
        
        private string fOTOPRODField;
        
        private string pREPRODField;
        
        private string sTKPRODField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CATPROD {
            get {
                return this.cATPRODField;
            }
            set {
                this.cATPRODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODPROD {
            get {
                return this.cODPRODField;
            }
            set {
                this.cODPRODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DESCPROD {
            get {
                return this.dESCPRODField;
            }
            set {
                this.dESCPRODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FOTOPROD {
            get {
                return this.fOTOPRODField;
            }
            set {
                this.fOTOPRODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PREPROD {
            get {
                return this.pREPRODField;
            }
            set {
                this.pREPRODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string STKPROD {
            get {
                return this.sTKPRODField;
            }
            set {
                this.sTKPRODField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans/xsd")]
    public partial class BeanCategoriaProd {
        
        private string cODCATField;
        
        private string dESCCATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODCAT {
            get {
                return this.cODCATField;
            }
            set {
                this.cODCATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DESCCAT {
            get {
                return this.dESCCATField;
            }
            set {
                this.dESCCATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans/xsd")]
    public partial class BeanPedidoTuneado {
        
        private string cLIENTEField;
        
        private string cODPEDIDOField;
        
        private string cODUSUARIOField;
        
        private string cORREOField;
        
        private string dNIField;
        
        private string dOMICILIOField;
        
        private string fECHAField;
        
        private string hORAField;
        
        private string mETODOENVIOField;
        
        private string mETODOPAGOField;
        
        private string mONTOField;
        
        private string rEFSEDEField;
        
        private string tELEFONOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODPEDIDO {
            get {
                return this.cODPEDIDOField;
            }
            set {
                this.cODPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODUSUARIO {
            get {
                return this.cODUSUARIOField;
            }
            set {
                this.cODUSUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CORREO {
            get {
                return this.cORREOField;
            }
            set {
                this.cORREOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DOMICILIO {
            get {
                return this.dOMICILIOField;
            }
            set {
                this.dOMICILIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HORA {
            get {
                return this.hORAField;
            }
            set {
                this.hORAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string METODOENVIO {
            get {
                return this.mETODOENVIOField;
            }
            set {
                this.mETODOENVIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string METODOPAGO {
            get {
                return this.mETODOPAGOField;
            }
            set {
                this.mETODOPAGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MONTO {
            get {
                return this.mONTOField;
            }
            set {
                this.mONTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string REFSEDE {
            get {
                return this.rEFSEDEField;
            }
            set {
                this.rEFSEDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TELEFONO {
            get {
                return this.tELEFONOField;
            }
            set {
                this.tELEFONOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans/xsd")]
    public partial class BeanPedido {
        
        private string cLIENTEField;
        
        private string cODPEDIDOField;
        
        private string fECPEDIDOField;
        
        private string mETODOENVIOField;
        
        private string mETODOPAGOField;
        
        private string mONTOField;
        
        private string sEDEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CLIENTE {
            get {
                return this.cLIENTEField;
            }
            set {
                this.cLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODPEDIDO {
            get {
                return this.cODPEDIDOField;
            }
            set {
                this.cODPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECPEDIDO {
            get {
                return this.fECPEDIDOField;
            }
            set {
                this.fECPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string METODOENVIO {
            get {
                return this.mETODOENVIOField;
            }
            set {
                this.mETODOENVIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string METODOPAGO {
            get {
                return this.mETODOPAGOField;
            }
            set {
                this.mETODOPAGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MONTO {
            get {
                return this.mONTOField;
            }
            set {
                this.mONTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SEDE {
            get {
                return this.sEDEField;
            }
            set {
                this.sEDEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://beans/xsd")]
    public partial class BeanCitaTuneado {
        
        private string cODUSUARIOField;
        
        private string cORREOField;
        
        private string dNIField;
        
        private string dOMICILIOField;
        
        private string eSTADO_ACTUALField;
        
        private string fECHAField;
        
        private string hORAField;
        
        private string lUGAR_ATENCIONField;
        
        private string nOM_CLIENTEField;
        
        private string nRO_CITAField;
        
        private string sEDEField;
        
        private string tELEFONOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODUSUARIO {
            get {
                return this.cODUSUARIOField;
            }
            set {
                this.cODUSUARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CORREO {
            get {
                return this.cORREOField;
            }
            set {
                this.cORREOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DOMICILIO {
            get {
                return this.dOMICILIOField;
            }
            set {
                this.dOMICILIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ESTADO_ACTUAL {
            get {
                return this.eSTADO_ACTUALField;
            }
            set {
                this.eSTADO_ACTUALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FECHA {
            get {
                return this.fECHAField;
            }
            set {
                this.fECHAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HORA {
            get {
                return this.hORAField;
            }
            set {
                this.hORAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LUGAR_ATENCION {
            get {
                return this.lUGAR_ATENCIONField;
            }
            set {
                this.lUGAR_ATENCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NOM_CLIENTE {
            get {
                return this.nOM_CLIENTEField;
            }
            set {
                this.nOM_CLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NRO_CITA {
            get {
                return this.nRO_CITAField;
            }
            set {
                this.nRO_CITAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SEDE {
            get {
                return this.sEDEField;
            }
            set {
                this.sEDEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TELEFONO {
            get {
                return this.tELEFONOField;
            }
            set {
                this.tELEFONOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void u_editarCompletedEventHandler(object sender, u_editarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class u_editarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal u_editarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ci_listarCompletedEventHandler(object sender, ci_listarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ci_listarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ci_listarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeanCitaTuneado[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeanCitaTuneado[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void listaBeanPedidoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void pro_autogeneraCompletedEventHandler(object sender, pro_autogeneraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pro_autogeneraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pro_autogeneraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ped_detalleCompletedEventHandler(object sender, ped_detalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ped_detalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ped_detalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeanPedidoTuneado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeanPedidoTuneado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cat_listarCompletedEventHandler(object sender, cat_listarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cat_listarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cat_listarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeanCategoriaProd[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeanCategoriaProd[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void listaBeanProductoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ped_listarCompletedEventHandler(object sender, ped_listarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ped_listarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ped_listarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeanPedidoTuneado[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeanPedidoTuneado[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void u_registrarCompletedEventHandler(object sender, u_registrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class u_registrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal u_registrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ped_registrarCompletedEventHandler(object sender, ped_registrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ped_registrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ped_registrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void pro_editarCompletedEventHandler(object sender, pro_editarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pro_editarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pro_editarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void u_logueoCompletedEventHandler(object sender, u_logueoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class u_logueoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal u_logueoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeanUsuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeanUsuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void listaBeanPedidoDetalleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void pro_inactivarCompletedEventHandler(object sender, pro_inactivarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pro_inactivarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pro_inactivarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void pro_listarCompletedEventHandler(object sender, pro_listarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pro_listarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pro_listarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeanProducto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeanProducto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void pro_registrarCompletedEventHandler(object sender, pro_registrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pro_registrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pro_registrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ci_cancelarCompletedEventHandler(object sender, ci_cancelarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ci_cancelarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ci_cancelarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void s_listarCompletedEventHandler(object sender, s_listarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class s_listarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal s_listarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeanSede[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeanSede[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ci_detalleCompletedEventHandler(object sender, ci_detalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ci_detalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ci_detalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeanCitaTuneado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeanCitaTuneado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ci_registrarCompletedEventHandler(object sender, ci_registrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ci_registrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ci_registrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591